"""Regression coverage for HG-041 (GitHub issue #86): aggregate Mozilla NSS SQL
database-set inventory in the crypto-inventory scanner.

The bounded claim under test is exactly: *this lexical directory contains the
supported canonical NSS SQL database-set layout (`cert9.db`, `key4.db`,
`pkcs11.txt`) and a structurally recognized NSS internal-module configuration
stanza.* Nothing here asserts that either database is internally valid
SQLite/NSS data, that any certificate or key exists, that a key could be
unlocked, or that any application uses the directory.

The positive fixture in `fixtures/crypto_inventory/nss_sql/valid_empty/` was
generated by real `certutil -N` and its `pkcs11.txt` bytes are used verbatim --
never rewritten into a synthetic "preferred" layout (see that directory's
PROVENANCE.md). Synthetic markers appear only as negative controls, explicitly
allowed whitespace/case variants, duplicate-field cases, stanza-boundary
adversarial cases, and nested NSS-argument cases.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

import harvestguard
import scanner.crypto_inventory as crypto_inventory
from finding_adapters import normalize_crypto_inventory_df
from scanner.crypto_detectors import FileContext
from scanner.crypto_inventory import (
    CRYPTO_DETECTORS,
    scan_crypto_inventory,
    scan_crypto_inventory_findings,
)
from scanner.errors import LocalScanError

RULE_ID = "nss:sql_database_set"
ASSET_TYPE = "NSS Cryptographic Database Set"
EVIDENCE = "Supported NSS SQL database set detected"
CONFIDENCE = "High"
FORMAT = "NSS SQL"
MARKER = "pkcs11.txt"
CERT_DB = "cert9.db"
KEY_DB = "key4.db"

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "crypto_inventory"
NSS_FIXTURE = FIXTURE_DIR / "nss_sql" / "valid_empty"

# Unique, greppable values seeded into marker content so the privacy tests can
# prove none of it reaches any output, persistence, or error surface.
CANARY_CONFIGDIR = "sql:/canary-configdir-4f21ab9c"
CANARY_ARGUMENT = "canary-argument-77bd30e1"
CANARY_LIBRARY = "/usr/lib/canary-library-15ce8804.so"
CANARY_GARBAGE = "canary-garbage-6a0d92f3"
CANARIES = (CANARY_CONFIGDIR, CANARY_ARGUMENT, CANARY_LIBRARY, CANARY_GARBAGE)

VALID_NAME = "NSS Internal PKCS #11 Module"
VALID_PARAMETERS = "configdir='sql:/tmp/nssdb' certPrefix='' keyPrefix='' flags="
VALID_NSS = (
    "Flags=internal,critical trustOrder=75 cipherOrder=100 "
    "slotParams=(1={slotFlags=[ECC,RSA,DSA] askpw=any timeout=30})"
)


# ---------------------------------------------------------------------------
# Fixtures and helpers
# ---------------------------------------------------------------------------


def _real_marker() -> bytes:
    """The committed, unmodified bytes real NSS tooling wrote."""
    return (NSS_FIXTURE / MARKER).read_bytes()


def _marker(
    library: str = "",
    name: str = VALID_NAME,
    parameters: str = VALID_PARAMETERS,
    nss: str = VALID_NSS,
) -> str:
    return (
        f"library={library}\n"
        f"name={name}\n"
        f"parameters={parameters}\n"
        f"NSS={nss}\n"
    )


def _root(
    tmp_path: Path,
    marker: str | bytes | None = "default",
    cert_db: bool = True,
    key_db: bool = True,
    name: str = "nssdb",
) -> Path:
    """A candidate lexical NSS root. `cert9.db`/`key4.db` stand in for real
    databases: HG-041 never opens them, so their content is irrelevant and
    deliberately not real NSS data."""
    root = tmp_path / name
    root.mkdir(parents=True, exist_ok=True)
    if marker is not None:
        data = _marker() if marker == "default" else marker
        if isinstance(data, str):
            (root / MARKER).write_text(data)
        else:
            (root / MARKER).write_bytes(data)
    if cert_db:
        (root / CERT_DB).write_bytes(b"SQLite format 3\x00 not-a-real-database")
    if key_db:
        (root / KEY_DB).write_bytes(b"SQLite format 3\x00 not-a-real-database")
    return root


def _real_root(tmp_path: Path, name: str = "nssdb") -> Path:
    """A root whose three files are the real `certutil -N` fixture bytes."""
    root = tmp_path / name
    root.mkdir(parents=True, exist_ok=True)
    for component in (MARKER, CERT_DB, KEY_DB):
        (root / component).write_bytes((NSS_FIXTURE / component).read_bytes())
    return root


def _records(path: Path, **kwargs) -> list[dict]:
    df = scan_crypto_inventory(str(path), **kwargs)
    return [] if df.empty else df.to_dict(orient="records")


def _nss_records(path: Path, **kwargs) -> list[dict]:
    return [r for r in _records(path, **kwargs) if r.get("Rule ID") == RULE_ID]


def _detector():
    return next(d for d in CRYPTO_DETECTORS if d.detector_id == RULE_ID)


# ---------------------------------------------------------------------------
# Real fixture: the grammar is fixture-grounded
# ---------------------------------------------------------------------------


def test_real_nss_fixture_is_committed_unmodified():
    """The marker under test is the one NSS wrote, not a rewritten variant."""
    marker = _real_marker()
    assert marker.startswith(b"library=\n")
    assert b"name=NSS Internal PKCS #11 Module\n" in marker
    assert b"parameters=configdir=" in marker
    assert b"\nNSS=Flags=internal,critical " in marker
    for component in (CERT_DB, KEY_DB):
        assert (NSS_FIXTURE / component).is_file()


def test_real_generated_marker_satisfies_the_written_grammar():
    text = _real_marker().decode("utf-8")
    assert crypto_inventory._nss_marker_has_supported_internal_module(text)


def test_real_fixture_directory_scan_emits_one_finding():
    records = _nss_records(NSS_FIXTURE)
    assert len(records) == 1
    assert records[0]["Location"] == str(NSS_FIXTURE)


def test_real_fixture_marker_scanned_directly_emits_one_finding():
    records = _nss_records(NSS_FIXTURE / MARKER)
    assert len(records) == 1
    # The location is the lexical containing directory, never the marker path.
    assert records[0]["Location"] == str(NSS_FIXTURE)


# ---------------------------------------------------------------------------
# Finding contract
# ---------------------------------------------------------------------------


def test_exact_finding_contract(tmp_path):
    root = _real_root(tmp_path)
    records = _nss_records(root)
    assert len(records) == 1
    record = records[0]
    assert record["Asset Type"] == ASSET_TYPE
    assert record["Rule ID"] == RULE_ID
    assert record["Confidence"] == CONFIDENCE
    assert record["Evidence"] == EVIDENCE
    assert record["Format"] == FORMAT
    assert record["Location"] == str(root)


def test_no_metadata_beyond_format_is_emitted(tmp_path):
    record = _nss_records(_root(tmp_path))[0]
    for key in (
        "Algorithm",
        "Key Size",
        "Signature Algorithm",
        "Expiration",
        "Issuer",
        "Subject",
        "Fingerprint",
        "Config Version",
        "Mode",
    ):
        assert record[key] is None
    assert record["Errors"] == ""


# ---------------------------------------------------------------------------
# Detector-framework contract
# ---------------------------------------------------------------------------


def test_detector_declaration_is_pinned():
    detector = _detector()
    assert detector.scope == "root"
    assert detector.detector_id == RULE_ID
    assert detector.rule_id == RULE_ID
    assert detector.marker_filename == MARKER
    assert detector.priority == 31
    assert detector.owns_marker is False
    assert detector.confidence == CONFIDENCE
    assert detector.evidence == EVIDENCE
    assert detector.metadata_keys == frozenset({"Format"})


def test_registry_position_is_after_gocryptfs_and_before_bcfks():
    priorities = {d.detector_id: d.priority for d in CRYPTO_DETECTORS}
    assert priorities["encrypted_filesystem:gocryptfs"] < priorities[RULE_ID]
    assert priorities[RULE_ID] < priorities["java_keystore:bcfks"]
    ordered = [d.detector_id for d in CRYPTO_DETECTORS]
    assert (
        ordered.index("encrypted_filesystem:gocryptfs")
        < ordered.index(RULE_ID)
        < ordered.index("java_keystore:bcfks")
    )


def test_no_file_level_nss_detector_exists():
    nss_detectors = [d for d in CRYPTO_DETECTORS if (d.rule_id or "").startswith("nss:")]
    assert [d.detector_id for d in nss_detectors] == [RULE_ID]
    assert all(d.scope == "root" for d in nss_detectors)


def test_cert9_and_key4_are_not_root_markers():
    markers = {d.marker_filename for d in CRYPTO_DETECTORS if d.scope == "root"}
    assert MARKER in markers
    assert CERT_DB not in markers
    assert KEY_DB not in markers


# ---------------------------------------------------------------------------
# Required root structure
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "cert_db,key_db,marker",
    [
        pytest.param(False, False, "default", id="marker-only"),
        pytest.param(True, False, "default", id="marker-and-cert9"),
        pytest.param(False, True, "default", id="marker-and-key4"),
        pytest.param(True, True, None, id="databases-without-marker"),
        pytest.param(True, False, None, id="only-cert9"),
        pytest.param(False, True, None, id="only-key4"),
    ],
)
def test_incomplete_sets_produce_no_finding(tmp_path, cert_db, key_db, marker):
    root = _root(tmp_path, marker=marker, cert_db=cert_db, key_db=key_db)
    assert _nss_records(root) == []


@pytest.mark.parametrize(
    "names",
    [
        pytest.param(("cert8.db", "key3.db"), id="legacy-dbm"),
        pytest.param(("cert8.db", "key3.db", "secmod.db"), id="legacy-dbm-secmod"),
        pytest.param(("foo-cert9.db", "foo-key4.db"), id="prefixed"),
        pytest.param(("cert9.db.bak", "key4.db.old"), id="backup-suffix"),
    ],
)
def test_noncanonical_database_names_produce_no_finding(tmp_path, names):
    root = _root(tmp_path, cert_db=False, key_db=False)
    for name in names:
        (root / name).write_bytes(b"not opened by HG-041")
    assert _nss_records(root) == []


def test_marker_suffix_variant_is_not_a_marker(tmp_path):
    root = _root(tmp_path, marker=None)
    (root / "pkcs11.txt~").write_text(_marker())
    assert _nss_records(root) == []


def test_components_in_different_directories_produce_no_finding(tmp_path):
    upper = _root(tmp_path, marker="default", cert_db=False, key_db=False)
    lower = upper / "child"
    lower.mkdir()
    (lower / CERT_DB).write_bytes(b"x")
    (lower / KEY_DB).write_bytes(b"x")
    assert _nss_records(tmp_path) == []


def test_parent_directory_is_not_searched_for_components(tmp_path):
    (tmp_path / CERT_DB).write_bytes(b"x")
    (tmp_path / KEY_DB).write_bytes(b"x")
    _root(tmp_path, marker="default", cert_db=False, key_db=False)
    assert _nss_records(tmp_path) == []


def test_arbitrary_sibling_files_plus_invalid_marker_produce_no_finding(tmp_path):
    root = _root(tmp_path, marker="not an NSS configuration at all\n")
    (root / "notes.txt").write_text("unrelated")
    assert _nss_records(root) == []


def test_accepted_false_positive_boundary_is_explicit(tmp_path):
    """Canonical-named arbitrary sibling files plus a structurally valid marker
    match. HG-041 never opens the databases, so this is an accepted and
    documented false positive rather than a defect."""
    root = _root(tmp_path)
    (root / CERT_DB).write_bytes(b"this is not a database at all")
    (root / KEY_DB).write_text("neither is this")
    assert len(_nss_records(root)) == 1


# ---------------------------------------------------------------------------
# Marker grammar: accepted forms
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "marker",
    [
        pytest.param(_marker(), id="canonical"),
        pytest.param(_marker().replace("\n", "\r\n"), id="crlf"),
        pytest.param(_marker().rstrip("\n"), id="no-final-newline"),
        pytest.param(_marker() + "\n\n", id="trailing-blank-lines"),
        pytest.param(
            "# a comment\n\n" + _marker().replace("name=", "# inline comment\nname="),
            id="comments-and-blank-lines",
        ),
        pytest.param(
            "LIBRARY=\nNaMe=" + VALID_NAME + "\nPARAMETERS=" + VALID_PARAMETERS
            + "\nnss=" + VALID_NSS + "\n",
            id="field-name-case-variants",
        ),
        pytest.param(_marker(name="NSS Internal PKCS 11 Module"), id="module-name-no-hash"),
        pytest.param(
            _marker(name="NSS  Internal\tPKCS #11   Module"),
            id="module-name-collapsed-whitespace",
        ),
        pytest.param("library=   \n" + _marker()[len("library=\n") :], id="library-spaces"),
        pytest.param(
            _marker() + "unknownRecord=whatever\n", id="unknown-record-in-stanza"
        ),
        pytest.param(
            _marker(nss="trustOrder=75 Flags=internal,critical"), id="flags-after-args"
        ),
        pytest.param(
            _marker(nss="Flags=internal,critical\ttrustOrder=75"), id="tab-separated-args"
        ),
        pytest.param(
            _marker(nss='Flags=internal,critical slotParams=(1={askpw="a\tb c"})'),
            id="tabs-inside-nested-and-quoted",
        ),
        pytest.param(
            _marker(nss="Flags=internal,critical,fips extra=(a{b[c]})"),
            id="extra-flag-token-and-nesting",
        ),
        pytest.param(
            _marker(nss="Flags=Internal,CRITICAL"), id="flag-token-case-insensitive"
        ),
        pytest.param(
            _marker(parameters=r"configdir='sql:C:\nss\db' certPrefix=''"),
            id="backslash-in-parameters",
        ),
        pytest.param(
            _marker(nss=r"Flags=internal,critical note=(a\b)"), id="backslash-in-nss"
        ),
        pytest.param(
            _marker(parameters='configdir="sql:/tmp/nssdb"'), id="double-quoted-configdir"
        ),
        pytest.param(
            _marker(parameters="configdir=sql:/tmp/nssdb"), id="unquoted-configdir"
        ),
    ],
)
def test_accepted_marker_forms(tmp_path, marker):
    root = _root(tmp_path, marker=marker)
    assert len(_nss_records(root)) == 1


def test_two_independently_valid_stanzas_still_emit_one_finding(tmp_path):
    root = _root(tmp_path, marker=_marker() + _marker())
    assert len(_nss_records(root)) == 1


def test_one_valid_stanza_among_several_modules_matches(tmp_path):
    marker = (
        _marker(library="/usr/lib/libexternal.so", nss="Flags=friendly")
        + _marker()
        + "library=/usr/lib/libother.so\nname=Other Module\n"
    )
    root = _root(tmp_path, marker=marker)
    assert len(_nss_records(root)) == 1


def test_zero_valid_stanzas_produce_no_finding(tmp_path):
    marker = _marker(library="/usr/lib/libexternal.so") + _marker(name="Other Module")
    assert _nss_records(_root(tmp_path, marker=marker)) == []


def test_incomplete_stanza_followed_by_valid_stanza_matches(tmp_path):
    marker = "library=\nname=" + VALID_NAME + "\n" + _marker()
    assert len(_nss_records(_root(tmp_path, marker=marker))) == 1


# ---------------------------------------------------------------------------
# Marker grammar: rejected forms
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "marker",
    [
        pytest.param("", id="empty"),
        pytest.param("arbitrary text\nwith no records\n", id="arbitrary-text"),
        pytest.param(_marker(library="/usr/lib/libsomething.so"), id="external-library"),
        pytest.param(_marker(library="libpkcs11.so"), id="external-library-bare"),
        pytest.param(_marker(name="Some Other Module"), id="wrong-module-name"),
        pytest.param(_marker(name="nss internal pkcs #11 module"), id="module-name-case"),
        pytest.param(
            "name=" + VALID_NAME + "\nparameters=" + VALID_PARAMETERS + "\nNSS=" + VALID_NSS,
            id="missing-library",
        ),
        pytest.param(
            "library=\nparameters=" + VALID_PARAMETERS + "\nNSS=" + VALID_NSS,
            id="missing-name",
        ),
        pytest.param(
            "library=\nname=" + VALID_NAME + "\nNSS=" + VALID_NSS, id="missing-parameters"
        ),
        pytest.param(
            "library=\nname=" + VALID_NAME + "\nparameters=" + VALID_PARAMETERS,
            id="missing-nss",
        ),
        pytest.param(_marker() + "name=" + VALID_NAME + "\n", id="duplicate-name"),
        pytest.param(
            _marker() + "parameters=" + VALID_PARAMETERS + "\n", id="duplicate-parameters"
        ),
        pytest.param(_marker() + "NSS=" + VALID_NSS + "\n", id="duplicate-nss"),
        pytest.param(
            _marker(parameters="configdir='sql:/a' configdir='sql:/b'"),
            id="duplicate-configdir",
        ),
        pytest.param(
            _marker(parameters="configdir='sql:/a' CONFIGDIR='sql:/a'"),
            id="duplicate-configdir-case-variant",
        ),
        pytest.param(
            _marker(nss="Flags=internal,critical Flags=internal,critical"),
            id="duplicate-flags",
        ),
        pytest.param(_marker(parameters="configdir="), id="empty-configdir"),
        pytest.param(_marker(parameters="configdir=''"), id="empty-single-quoted-configdir"),
        pytest.param(_marker(parameters='configdir=""'), id="empty-double-quoted-configdir"),
        pytest.param(_marker(parameters="notconfigdir='sql:/a'"), id="notconfigdir"),
        pytest.param(_marker(parameters="myconfigdir='sql:/a'"), id="myconfigdir"),
        pytest.param(_marker(parameters="configdirectory='sql:/a'"), id="configdirectory"),
        pytest.param(_marker(parameters="certPrefix=''"), id="no-configdir"),
        pytest.param(_marker(parameters="configdir=abc'd ef'"), id="mixed-quoted-fragments"),
        pytest.param(_marker(parameters="configdir='abc'd"), id="trailing-unquoted-fragment"),
        pytest.param(_marker(parameters="configdir='sql:/a"), id="unmatched-quote"),
        pytest.param(_marker(nss="Flags=critical"), id="missing-internal"),
        pytest.param(_marker(nss="Flags=internal"), id="missing-critical"),
        pytest.param(_marker(nss="Flags=notinternal,critical"), id="notinternal"),
        pytest.param(_marker(nss="Flags=internal,criticality"), id="criticality"),
        pytest.param(_marker(nss="Flags=internally,critical"), id="internally"),
        pytest.param(_marker(nss='Flags="internal,critical"'), id="double-quoted-flags"),
        pytest.param(_marker(nss="Flags='internal,critical'"), id="single-quoted-flags"),
        pytest.param(
            _marker(nss='slotParams=(1={note="Flags=internal,critical"})'),
            id="flags-inside-quotes",
        ),
        pytest.param(
            _marker(nss="slotParams=(1={Flags=internal,critical})"),
            id="flags-inside-nesting",
        ),
        pytest.param(_marker(nss="Flags=internal,critical extra=(a"), id="unbalanced-paren"),
        pytest.param(_marker(nss="Flags=internal,critical extra=a)"), id="stray-close"),
        pytest.param(_marker(nss="Flags=internal,critical extra=[a"), id="unbalanced-bracket"),
        pytest.param(_marker(nss="Flags=internal,critical extra={a"), id="unbalanced-brace"),
        pytest.param(_marker(nss="Flags=internal,critical extra='a"), id="nss-unmatched-quote"),
        pytest.param(_marker(nss="Flags=internal,critical extra=([)]"), id="cross-nested-1"),
        pytest.param(_marker(nss="Flags=internal,critical extra={(})"), id="cross-nested-2"),
        pytest.param(_marker(nss="Flags=internal,critical extra=[(])"), id="cross-nested-3"),
        pytest.param(_marker(nss="trustOrder=75"), id="no-flags-argument"),
        pytest.param(
            "library=\nname=" + VALID_NAME + "\nlibrary=\nparameters="
            + VALID_PARAMETERS + "\nNSS=" + VALID_NSS,
            id="records-split-across-stanzas",
        ),
        pytest.param(
            "name=" + VALID_NAME + "\nparameters=" + VALID_PARAMETERS + "\nNSS="
            + VALID_NSS + "\nlibrary=\n",
            id="records-before-first-library-discarded",
        ),
        pytest.param(
            "LIBRARY=\nname=" + VALID_NAME + "\nlibrary=\nparameters="
            + VALID_PARAMETERS + "\nNSS=" + VALID_NSS,
            id="case-variant-library-starts-new-stanza",
        ),
    ],
)
def test_rejected_marker_forms(tmp_path, marker):
    root = _root(tmp_path, marker=marker)
    assert _nss_records(root) == []


def test_binary_marker_has_no_text_evidence(tmp_path):
    root = _root(tmp_path, marker=_marker().encode("utf-8").replace(b"library", b"lib\x00ary"))
    assert _nss_records(root) == []


# ---------------------------------------------------------------------------
# Aggregate identity: one finding per lexical root
# ---------------------------------------------------------------------------


def test_visiting_all_three_files_does_not_amplify(tmp_path):
    root = _real_root(tmp_path)
    stats: dict[str, int] = {}
    records = _records(root, stats=stats)
    assert stats["files_inspected"] == 3
    assert len([r for r in records if r["Rule ID"] == RULE_ID]) == 1


def test_two_lexical_roots_emit_two_findings(tmp_path):
    _root(tmp_path, name="first")
    _root(tmp_path, name="second")
    records = _nss_records(tmp_path)
    assert len(records) == 2
    assert {r["Location"] for r in records} == {
        str(tmp_path / "first"),
        str(tmp_path / "second"),
    }


def test_nested_roots_are_independent(tmp_path):
    outer = _root(tmp_path, name="outer")
    _root(outer, name="inner")
    records = _nss_records(tmp_path)
    assert {r["Location"] for r in records} == {str(outer), str(outer / "inner")}


def test_repeated_scans_produce_deterministic_finding_ids(tmp_path):
    root = _root(tmp_path)
    first = [f.finding_id for f in scan_crypto_inventory_findings(str(root))]
    second = [f.finding_id for f in scan_crypto_inventory_findings(str(root))]
    assert first == second
    assert len(first) == 1
    assert len(first[0]) == 64


def test_moving_the_set_changes_identity(tmp_path):
    first = _root(tmp_path, name="here")
    original = scan_crypto_inventory_findings(str(first))[0].finding_id
    moved = _root(tmp_path, name="there")
    relocated = scan_crypto_inventory_findings(str(moved))[0].finding_id
    assert original != relocated


# ---------------------------------------------------------------------------
# Symlink semantics
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("follow", [False, True])
def test_marker_symlink_never_triggers(tmp_path, follow):
    real = _root(tmp_path, name="real")
    alias = tmp_path / "alias"
    alias.mkdir()
    (alias / MARKER).symlink_to(real / MARKER)
    (alias / CERT_DB).write_bytes(b"x")
    (alias / KEY_DB).write_bytes(b"x")
    records = _nss_records(alias, follow_symlinks=follow)
    assert records == []


def test_direct_scan_of_a_marker_symlink_never_triggers(tmp_path):
    real = _root(tmp_path, name="real")
    alias = tmp_path / "alias"
    alias.mkdir()
    (alias / MARKER).symlink_to(real / MARKER)
    (alias / CERT_DB).write_bytes(b"x")
    (alias / KEY_DB).write_bytes(b"x")
    assert _nss_records(alias / MARKER, follow_symlinks=True) == []


@pytest.mark.parametrize("sibling", [CERT_DB, KEY_DB])
@pytest.mark.parametrize("follow", [False, True])
def test_symlinked_sibling_does_not_satisfy_the_set(tmp_path, sibling, follow):
    source = tmp_path / "source"
    source.mkdir()
    (source / sibling).write_bytes(b"x")
    root = _root(tmp_path, cert_db=sibling != CERT_DB, key_db=sibling != KEY_DB)
    (root / sibling).symlink_to(source / sibling)
    assert _nss_records(root, follow_symlinks=follow) == []


def test_directory_symlink_aliases_are_distinct_lexical_roots(tmp_path):
    target = tmp_path / "target"
    target.mkdir()
    real = _root(target, name="real")
    (target / "alias").symlink_to(real, target_is_directory=True)

    without = _nss_records(target)
    assert [r["Location"] for r in without] == [str(real)]

    findings = scan_crypto_inventory_findings(str(target), follow_symlinks=True)
    nss = [f for f in findings if f.rule_id == RULE_ID]
    assert {f.location for f in nss} == {str(real), str(target / "alias")}
    # No realpath/inode deduplication: two lexical paths, two finding IDs.
    assert len({f.finding_id for f in nss}) == 2


# ---------------------------------------------------------------------------
# Exclusion semantics
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "pattern",
    [
        pytest.param(MARKER, id="marker"),
        pytest.param(CERT_DB, id="cert9"),
        pytest.param(KEY_DB, id="key4"),
        pytest.param("nssdb", id="root-directory"),
        pytest.param("*.db", id="wildcard-databases"),
        pytest.param("pkcs11.*", id="wildcard-marker"),
        pytest.param("nssdb/cert9.db", id="root-relative-path"),
    ],
)
def test_excluded_components_suppress_the_aggregate(tmp_path, pattern):
    _root(tmp_path)
    assert _nss_records(tmp_path, exclude_patterns=[pattern]) == []


def test_unrelated_exclusion_leaves_the_aggregate_intact(tmp_path):
    _root(tmp_path)
    assert len(_nss_records(tmp_path, exclude_patterns=["*.pem", "other/*"])) == 1


@pytest.mark.parametrize("sibling", [CERT_DB, KEY_DB])
def test_direct_marker_scan_honors_basename_sibling_exclusion(tmp_path, sibling):
    root = _root(tmp_path)
    assert _nss_records(root / MARKER, exclude_patterns=[sibling]) == []


def test_direct_marker_scan_sibling_match_path_is_the_bare_basename(tmp_path):
    """For a direct-file target the sibling match path is exactly `cert9.db`,
    with no parent prefix -- so a root-relative pattern that would match during
    a directory scan does not match here."""
    root = _root(tmp_path)
    assert len(_nss_records(root / MARKER, exclude_patterns=["nssdb/cert9.db"])) == 1
    # The same pattern does suppress the aggregate when the scan is the
    # directory walk that would assign that root-relative match path.
    assert _nss_records(tmp_path, exclude_patterns=["nssdb/cert9.db"]) == []


def test_sibling_eligibility_uses_the_scanner_exclusion_matcher(tmp_path, monkeypatch):
    root = _root(tmp_path)
    seen: list[tuple[str, str]] = []
    original = crypto_inventory._is_excluded

    def _recording(path, match_path, patterns):
        seen.append((path.name, match_path))
        return original(path, match_path, patterns)

    monkeypatch.setattr(crypto_inventory, "_is_excluded", _recording)
    assert len(_nss_records(root / MARKER, exclude_patterns=["nothing"])) == 1
    assert (CERT_DB, CERT_DB) in seen
    assert (KEY_DB, KEY_DB) in seen


def test_eligible_sibling_helper_stays_a_fixed_name_check(tmp_path):
    """The narrow framework extension HG-041 authorized: a bare-filename,
    no-listing, no-open eligibility question -- never a traversal primitive."""
    root = _root(tmp_path)
    context = FileContext(root / MARKER).root_context()
    assert context.has_eligible_regular_sibling(CERT_DB) is True
    assert context.has_eligible_regular_sibling("missing.db") is False
    for rejected in ("../cert9.db", "sub/cert9.db", "", ".", ".."):
        with pytest.raises(ValueError):
            context.has_eligible_regular_sibling(rejected)


def test_eligible_sibling_helper_applies_the_scans_exclusions(tmp_path):
    root = _root(tmp_path)
    scope = crypto_inventory._scan_scope(root, [CERT_DB])
    context = FileContext(root / MARKER, scope=scope).root_context()
    assert context.has_eligible_regular_sibling(CERT_DB) is False
    assert context.has_eligible_regular_sibling(KEY_DB) is True


# ---------------------------------------------------------------------------
# Accounting
# ---------------------------------------------------------------------------


def test_direct_marker_scan_inspects_exactly_one_file(tmp_path):
    root = _root(tmp_path)
    stats: dict[str, int] = {}
    records = _nss_records(root / MARKER, stats=stats)
    assert stats["files_inspected"] == 1
    assert len(records) == 1


def test_sibling_checks_do_not_open_the_databases(tmp_path, monkeypatch):
    root = _root(tmp_path)
    opened: list[str] = []
    real_open = Path.open
    real_read_bytes = Path.read_bytes

    def _tracking_open(self, *args, **kwargs):
        opened.append(self.name)
        return real_open(self, *args, **kwargs)

    def _tracking_read_bytes(self):
        opened.append(self.name)
        return real_read_bytes(self)

    monkeypatch.setattr(Path, "open", _tracking_open)
    monkeypatch.setattr(Path, "read_bytes", _tracking_read_bytes)
    assert len(_nss_records(root / MARKER)) == 1
    assert CERT_DB not in opened
    assert KEY_DB not in opened


# ---------------------------------------------------------------------------
# Ownership, precedence, and coexistence
# ---------------------------------------------------------------------------


def test_rejected_marker_falls_through_to_the_certificate_detector(tmp_path):
    certificate = (FIXTURE_DIR / "rsa_cert.pem").read_text()
    root = _root(tmp_path, marker=certificate)
    records = _records(root)
    assert [r for r in records if r["Rule ID"] == RULE_ID] == []
    assert any(r["Asset Type"] == "PEM Certificate" for r in records)


def test_rejected_marker_falls_through_to_the_private_key_detector(tmp_path):
    key = (FIXTURE_DIR / "valid_key.pem").read_text()
    root = _root(tmp_path, marker=key)
    records = _records(root)
    assert [r for r in records if r["Rule ID"] == RULE_ID] == []
    assert any("Private Key" in r["Asset Type"] for r in records)


def test_validated_root_is_terminal_for_the_marker(tmp_path):
    certificate = (FIXTURE_DIR / "rsa_cert.pem").read_text()
    root = _root(tmp_path, marker=_marker() + certificate)
    records = _records(root)
    assert len([r for r in records if r["Rule ID"] == RULE_ID]) == 1
    assert not any(r["Asset Type"] == "PEM Certificate" for r in records)


def test_earlier_terminal_detector_retains_precedence(tmp_path):
    root = _root(tmp_path, marker=b"Salted__" + b"\x01" * 32)
    records = _records(root)
    assert [r["Rule ID"] for r in records] == ["encrypted_file:openssl"]


def test_independent_component_finding_may_coexist(tmp_path):
    """A non-NSS detector's defensible finding about a component file is
    evidence coexistence, not duplicate NSS inventory."""
    root = _root(tmp_path)
    (root / CERT_DB).write_bytes((FIXTURE_DIR / "rsa_cert.pem").read_bytes())
    records = _records(root)
    assert len([r for r in records if r["Rule ID"] == RULE_ID]) == 1
    assert any(r["Asset Type"] == "PEM Certificate" for r in records)
    assert all(
        r["Rule ID"] == RULE_ID or not (r["Rule ID"] or "").startswith("nss:")
        for r in records
    )


# ---------------------------------------------------------------------------
# Runtime security boundary
# ---------------------------------------------------------------------------


def test_no_nss_sqlite_or_subprocess_interface_is_invoked(tmp_path, monkeypatch):
    import ctypes
    import ctypes.util
    import sqlite3

    def _forbidden(name):
        def _raise(*args, **kwargs):
            raise AssertionError(f"HG-041 must never call {name}")

        return _raise

    monkeypatch.setattr(sqlite3, "connect", _forbidden("sqlite3.connect"))
    monkeypatch.setattr(subprocess, "run", _forbidden("subprocess.run"))
    monkeypatch.setattr(subprocess, "Popen", _forbidden("subprocess.Popen"))
    monkeypatch.setattr(subprocess, "check_output", _forbidden("subprocess.check_output"))
    monkeypatch.setattr(ctypes, "CDLL", _forbidden("ctypes.CDLL"))
    monkeypatch.setattr(ctypes.util, "find_library", _forbidden("ctypes.util.find_library"))

    root = _real_root(tmp_path)
    assert len(_nss_records(root)) == 1


def test_no_password_environment_variable_is_read(tmp_path, monkeypatch):
    reads: list[str] = []
    import os as os_module

    real_getenv = os_module.getenv

    def _tracking_getenv(key, *args, **kwargs):
        reads.append(key)
        return real_getenv(key, *args, **kwargs)

    monkeypatch.setattr(os_module, "getenv", _tracking_getenv)
    root = _real_root(tmp_path)
    assert len(_nss_records(root)) == 1
    assert not any("PASS" in key.upper() or "PIN" in key.upper() for key in reads)


def test_no_files_are_written_beside_the_databases(tmp_path):
    root = _real_root(tmp_path)
    before = sorted(p.name for p in root.iterdir())
    assert len(_nss_records(root)) == 1
    after = sorted(p.name for p in root.iterdir())
    assert before == after
    # No SQLite journal or WAL sidecar was created.
    assert not any(name.endswith(("-journal", "-wal", "-shm")) for name in after)


def test_marker_is_read_but_databases_are_never_touched(tmp_path, monkeypatch):
    root = _real_root(tmp_path)
    read_names: list[str] = []
    real_read_bytes = Path.read_bytes

    def _tracking(self):
        read_names.append(self.name)
        return real_read_bytes(self)

    monkeypatch.setattr(Path, "read_bytes", _tracking)
    assert len(_nss_records(root / MARKER)) == 1
    assert read_names == [MARKER]


# ---------------------------------------------------------------------------
# Normalization, evidence store, privacy
# ---------------------------------------------------------------------------


def test_normalized_finding_contract(tmp_path):
    root = _real_root(tmp_path)
    findings = [
        f for f in scan_crypto_inventory_findings(str(root), scan_id="scan-1")
        if f.rule_id == RULE_ID
    ]
    assert len(findings) == 1
    finding = findings[0]
    assert finding.source_type == "crypto_inventory"
    assert finding.asset_type == ASSET_TYPE
    assert finding.rule_id == RULE_ID
    assert finding.confidence == CONFIDENCE
    assert finding.evidence == EVIDENCE
    assert finding.technical_metadata.get("Format") == FORMAT
    assert finding.location == str(root)
    assert finding.scan_id == "scan-1"
    assert finding.finding_id


def _canary_root(tmp_path: Path, name: str = "nssdb") -> Path:
    marker = _marker(
        parameters=f"configdir='{CANARY_CONFIGDIR}' certPrefix='{CANARY_ARGUMENT}'",
        nss=(
            "Flags=internal,critical trustOrder=75 "
            f"slotParams=(1={{askpw=any note='{CANARY_ARGUMENT}'}})"
        ),
    )
    return _root(tmp_path, marker=marker, name=name)


def test_canaries_do_not_reach_findings_or_dataframe(tmp_path):
    root = _canary_root(tmp_path)
    df = scan_crypto_inventory(str(root))
    payload = df.to_json()
    for canary in CANARIES:
        assert canary not in payload
    normalized = normalize_crypto_inventory_df(df)
    assert json.dumps([f.to_dict() for f in normalized]).count(CANARY_CONFIGDIR) == 0


def test_canaries_do_not_reach_cli_json_or_markdown(tmp_path, capsys):
    target = tmp_path / "target"
    _canary_root(target)
    # A rejected external-library stanza and arbitrary garbage, both carrying
    # their own canaries, alongside the accepted root.
    rejected = _root(
        target,
        marker=_marker(library=CANARY_LIBRARY),
        name="rejected",
    )
    (rejected / "garbage.txt").write_text(CANARY_GARBAGE)

    assert harvestguard.main(["scan", str(target), "--type", "crypto", "--json", "--quiet"]) == 0
    payload = capsys.readouterr().out
    assert RULE_ID in payload
    for canary in CANARIES:
        assert canary not in payload

    assert harvestguard.main(["scan", str(target), "--type", "crypto", "--quiet"]) == 0
    markdown = capsys.readouterr().out
    for canary in CANARIES:
        assert canary not in markdown


def test_evidence_store_round_trip_preserves_the_finding(tmp_path, capsys):
    """Real evidence-db scan -> verify -> JSON/Markdown export for HG-041."""
    target = tmp_path / "target"
    target.mkdir()
    root = _canary_root(target)
    db = tmp_path / "evidence.db"

    assert (
        harvestguard.main(
            [
                "scan",
                str(target),
                "--type",
                "crypto",
                "--json",
                "--quiet",
                "--evidence-db",
                str(db),
            ]
        )
        == 0
    )
    live = capsys.readouterr().out
    records = [r for r in json.loads(live) if r["rule_id"] == RULE_ID]
    assert len(records) == 1
    record = records[0]
    scan_id = record["scan_id"]
    assert scan_id
    assert record["source_type"] == "crypto_inventory"
    assert record["asset_type"] == ASSET_TYPE
    assert record["confidence"] == CONFIDENCE
    assert record["evidence"] == EVIDENCE
    assert record["technical_metadata"]["Format"] == FORMAT
    assert record["location"] == str(root)

    assert harvestguard.main(["evidence", "verify", scan_id, "--evidence-db", str(db)]) == 0
    capsys.readouterr()

    assert (
        harvestguard.main(
            ["evidence", "export", scan_id, "--evidence-db", str(db), "--json", "--quiet"]
        )
        == 0
    )
    stored = capsys.readouterr().out
    assert stored == live
    stored_record = [r for r in json.loads(stored) if r["rule_id"] == RULE_ID][0]
    assert stored_record["evidence"] == EVIDENCE
    metadata = stored_record["technical_metadata"]
    assert metadata["Format"] == FORMAT
    # Nothing beyond Format survives persistence: every other metadata key the
    # schema carries is unset for this finding.
    assert {k: v for k, v in metadata.items() if v is not None} == {"Format": FORMAT}

    assert (
        harvestguard.main(
            ["evidence", "export", scan_id, "--evidence-db", str(db), "--markdown", "--quiet"]
        )
        == 0
    )
    markdown = capsys.readouterr().out
    assert ASSET_TYPE in markdown
    assert EVIDENCE in markdown

    for payload in (live, stored, markdown):
        for canary in CANARIES:
            assert canary not in payload


def test_detector_failure_reports_the_root_location_without_content(tmp_path, monkeypatch):
    root = _canary_root(tmp_path)

    def _boom(text):
        raise ValueError(f"parser choked on {CANARY_CONFIGDIR}")

    monkeypatch.setattr(
        crypto_inventory, "_nss_marker_has_supported_internal_module", _boom
    )
    with pytest.raises(LocalScanError) as excinfo:
        scan_crypto_inventory_findings(str(root))
    message = str(excinfo.value)
    assert RULE_ID in message
    assert "ValueError" in message
    assert str(root) in message
    # The marker path is never the detector location for a root-parser failure.
    assert str(root / MARKER) not in message
    for canary in CANARIES:
        assert canary not in message
